import { env } from "cloudflare:workers";

export const alertDistricts = ["All districts", "Mae Sot", "Umphang", "Tha Song Yang", "Mae Ramat", "Phop Phra"] as const;
export const alertLanguages = ["en", "my", "th"] as const;
export const alertSeverities = ["watch", "warning", "critical"] as const;

export type AlertDistrict = typeof alertDistricts[number];
export type AlertLanguage = typeof alertLanguages[number];
export type AlertSeverity = typeof alertSeverities[number];

export type WarningAlertRecord = {
  id: string;
  status: "draft" | "published" | "expired";
  severity: AlertSeverity;
  district: AlertDistrict;
  titleEn: string;
  titleMy: string;
  titleTh: string;
  bodyEn: string;
  bodyMy: string;
  bodyTh: string;
  sourceName: string;
  sourceUrl: string | null;
  observedAt: string | null;
  createdAt: string;
  publishedAt: string | null;
  expiresAt: string;
  createdBy: string;
  triggerKey: string | null;
  autoGenerated: boolean;
};

export type AlertSubscriptionRecord = {
  id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  district: AlertDistrict;
  language: AlertLanguage;
};

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS warning_alerts (
    id TEXT PRIMARY KEY NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    severity TEXT NOT NULL,
    district TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_my TEXT NOT NULL,
    title_th TEXT NOT NULL,
    body_en TEXT NOT NULL,
    body_my TEXT NOT NULL,
    body_th TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_url TEXT,
    observed_at TEXT,
    created_at TEXT NOT NULL,
    published_at TEXT,
    expires_at TEXT NOT NULL,
    created_by TEXT NOT NULL,
    trigger_key TEXT UNIQUE,
    auto_generated INTEGER NOT NULL DEFAULT 0
  )`,
  "CREATE INDEX IF NOT EXISTS warning_alerts_status_published_idx ON warning_alerts (status, published_at)",
  "CREATE INDEX IF NOT EXISTS warning_alerts_district_expires_idx ON warning_alerts (district, expires_at)",
  `CREATE TABLE IF NOT EXISTS alert_subscriptions (
    id TEXT PRIMARY KEY NOT NULL,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    district TEXT NOT NULL,
    language TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    consented_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_error TEXT
  )`,
  "CREATE INDEX IF NOT EXISTS alert_subscriptions_active_district_idx ON alert_subscriptions (active, district)",
  `CREATE TABLE IF NOT EXISTS alert_deliveries (
    id TEXT PRIMARY KEY NOT NULL,
    alert_id TEXT NOT NULL,
    subscription_id TEXT NOT NULL,
    status TEXT NOT NULL,
    attempted_at TEXT NOT NULL,
    response_code INTEGER,
    error TEXT
  )`,
  "CREATE INDEX IF NOT EXISTS alert_deliveries_alert_idx ON alert_deliveries (alert_id, attempted_at)",
] as const;

let schemaReady: Promise<unknown> | null = null;

function ensureSchema() {
  schemaReady ??= env.DB.batch(schemaStatements.map((statement) => env.DB.prepare(statement))).catch((error: unknown) => {
    schemaReady = null;
    throw error;
  });
  return schemaReady;
}

function mapAlert(row: Record<string, unknown>): WarningAlertRecord {
  return {
    id: String(row.id),
    status: String(row.status) as WarningAlertRecord["status"],
    severity: String(row.severity) as AlertSeverity,
    district: String(row.district) as AlertDistrict,
    titleEn: String(row.title_en),
    titleMy: String(row.title_my),
    titleTh: String(row.title_th),
    bodyEn: String(row.body_en),
    bodyMy: String(row.body_my),
    bodyTh: String(row.body_th),
    sourceName: String(row.source_name),
    sourceUrl: row.source_url == null ? null : String(row.source_url),
    observedAt: row.observed_at == null ? null : String(row.observed_at),
    createdAt: String(row.created_at),
    publishedAt: row.published_at == null ? null : String(row.published_at),
    expiresAt: String(row.expires_at),
    createdBy: String(row.created_by),
    triggerKey: row.trigger_key == null ? null : String(row.trigger_key),
    autoGenerated: Boolean(row.auto_generated),
  };
}

export async function listPublishedAlerts(district?: AlertDistrict) {
  await ensureSchema();
  const now = new Date().toISOString();
  const query = district && district !== "All districts"
    ? env.DB.prepare(`SELECT * FROM warning_alerts WHERE status = 'published' AND expires_at > ? AND (district = 'All districts' OR district = ?) ORDER BY published_at DESC LIMIT 20`).bind(now, district)
    : env.DB.prepare(`SELECT * FROM warning_alerts WHERE status = 'published' AND expires_at > ? ORDER BY published_at DESC LIMIT 20`).bind(now);
  const result = await query.all() as { results: Record<string, unknown>[] };
  return result.results.map(mapAlert);
}

export async function listAlertsForAdmin() {
  await ensureSchema();
  const result = await env.DB.prepare("SELECT * FROM warning_alerts ORDER BY created_at DESC LIMIT 100").all() as { results: Record<string, unknown>[] };
  return result.results.map(mapAlert);
}

export async function getWarningAlert(id: string) {
  await ensureSchema();
  const row = await env.DB.prepare("SELECT * FROM warning_alerts WHERE id = ?").bind(id).first() as Record<string, unknown> | null;
  return row ? mapAlert(row) : null;
}

export async function createWarningAlert(alert: WarningAlertRecord) {
  await ensureSchema();
  await env.DB.prepare(`INSERT INTO warning_alerts (
    id, status, severity, district, title_en, title_my, title_th, body_en, body_my,
    body_th, source_name, source_url, observed_at, created_at, published_at, expires_at,
    created_by, trigger_key, auto_generated
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(
      alert.id, alert.status, alert.severity, alert.district, alert.titleEn, alert.titleMy,
      alert.titleTh, alert.bodyEn, alert.bodyMy, alert.bodyTh, alert.sourceName,
      alert.sourceUrl, alert.observedAt, alert.createdAt, alert.publishedAt, alert.expiresAt,
      alert.createdBy, alert.triggerKey, alert.autoGenerated ? 1 : 0,
    ).run();
  return alert;
}

export async function createAutomatedDraft(alert: WarningAlertRecord) {
  await ensureSchema();
  const result = await env.DB.prepare(`INSERT OR IGNORE INTO warning_alerts (
    id, status, severity, district, title_en, title_my, title_th, body_en, body_my,
    body_th, source_name, source_url, observed_at, created_at, published_at, expires_at,
    created_by, trigger_key, auto_generated
  ) VALUES (?, 'draft', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, 1)`)
    .bind(
      alert.id, alert.severity, alert.district, alert.titleEn, alert.titleMy, alert.titleTh,
      alert.bodyEn, alert.bodyMy, alert.bodyTh, alert.sourceName, alert.sourceUrl,
      alert.observedAt, alert.createdAt, alert.expiresAt, alert.createdBy, alert.triggerKey,
    ).run();
  return Number(result.meta.changes ?? 0) > 0;
}

export async function publishWarningAlert(id: string, publishedBy: string) {
  await ensureSchema();
  const publishedAt = new Date().toISOString();
  await env.DB.prepare("UPDATE warning_alerts SET status = 'published', published_at = ?, created_by = ? WHERE id = ? AND status = 'draft'")
    .bind(publishedAt, publishedBy, id).run();
  return getWarningAlert(id);
}

export async function expireWarningAlert(id: string) {
  await ensureSchema();
  await env.DB.prepare("UPDATE warning_alerts SET status = 'expired' WHERE id = ?").bind(id).run();
  return getWarningAlert(id);
}

export async function upsertAlertSubscription(subscription: AlertSubscriptionRecord) {
  await ensureSchema();
  const now = new Date().toISOString();
  await env.DB.prepare(`INSERT INTO alert_subscriptions (
    id, endpoint, p256dh, auth, district, language, active, consented_at, updated_at, last_error
  ) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?, NULL)
  ON CONFLICT(endpoint) DO UPDATE SET
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    district = excluded.district,
    language = excluded.language,
    active = 1,
    updated_at = excluded.updated_at,
    last_error = NULL`)
    .bind(subscription.id, subscription.endpoint, subscription.p256dh, subscription.auth, subscription.district, subscription.language, now, now)
    .run();
}

export async function deactivateAlertSubscription(endpoint: string, error: string | null = null) {
  await ensureSchema();
  await env.DB.prepare("UPDATE alert_subscriptions SET active = 0, updated_at = ?, last_error = ? WHERE endpoint = ?")
    .bind(new Date().toISOString(), error, endpoint).run();
}

export async function listSubscriptionsForAlert(district: AlertDistrict): Promise<AlertSubscriptionRecord[]> {
  await ensureSchema();
  const query = district === "All districts"
    ? env.DB.prepare("SELECT id, endpoint, p256dh, auth, district, language FROM alert_subscriptions WHERE active = 1 LIMIT 5000")
    : env.DB.prepare("SELECT id, endpoint, p256dh, auth, district, language FROM alert_subscriptions WHERE active = 1 AND (district = 'All districts' OR district = ?) LIMIT 5000").bind(district);
  const result = await query.all() as { results: Record<string, unknown>[] };
  return result.results.map((row: Record<string, unknown>) => ({
    id: String(row.id),
    endpoint: String(row.endpoint),
    p256dh: String(row.p256dh),
    auth: String(row.auth),
    district: String(row.district) as AlertDistrict,
    language: String(row.language) as AlertLanguage,
  }));
}

export async function recordAlertDelivery(input: {
  alertId: string;
  subscriptionId: string;
  status: "sent" | "failed";
  responseCode: number | null;
  error: string | null;
}) {
  await ensureSchema();
  await env.DB.prepare("INSERT INTO alert_deliveries (id, alert_id, subscription_id, status, attempted_at, response_code, error) VALUES (?, ?, ?, ?, ?, ?, ?)")
    .bind(crypto.randomUUID(), input.alertId, input.subscriptionId, input.status, new Date().toISOString(), input.responseCode, input.error?.slice(0, 500) ?? null)
    .run();
}
